import type { Review } from "./types";

/**
 * Fixture rows for the in-memory dev/test stub (`backend-stub.ts`). 24 rows
 * — enough to exercise more than one page of pagination at the contract's
 * documented `per_page=10` default — spanning a realistic ratings spread
 * (mostly 5s/4s with a couple of lower scores, matching how a real Google
 * Business Profile trends), a few with `reply_body` set and most without,
 * and `published_at` already in descending order (the stub doesn't re-sort,
 * same "fixture data pre-shaped to match the documented order" convention
 * `lib/content/fixtures.ts` already establishes for its own domain).
 *
 * None of these represent a hidden/moderated-out review — per the contract,
 * hidden rows are excluded server-side and this stub only models what a
 * caller can ever see, same posture the real endpoint documents for itself.
 *
 * **`body`/`review_url` nullability, exercised deliberately (not just the
 * happy path)** — confirmed against the real `Review` model/migration and
 * `SyncGoogleReviewsCommand::upsert()`'s own docblock that both are
 * genuinely nullable, and that `review_url` is expected `null` on
 * essentially every real synced row (Google's actual API doesn't appear to
 * return a `reviewUrl` field at all). Ids 37 and 20 model `review_url:
 * null` (id 20 also `body: null`, a ratings-only review with no written
 * comment) — id 20's shape doubles as "both nullable fields absent at
 * once", not just one at a time. The remaining rows keep `review_url` set
 * so the "View on Google" link's happy path stays exercised too, but this
 * is a stub convenience, not a claim about the real data's actual ratio.
 */
export const FIXTURE_REVIEWS: Review[] = [
  {
    id: 41,
    source: "google",
    author_name: "J. Smith",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-41",
    rating: 5,
    body: "Great service, turned up right on time and had my tyres swapped in the driveway in under 40 minutes. Wouldn't go anywhere else now.",
    reply_body: "Thanks so much for the kind words, J! See you next time.",
    review_url: "https://g.page/r/fixture-review-41",
    published_at: "2026-09-14T10:00:00+10:00",
  },
  {
    id: 40,
    source: "google",
    author_name: "Priya R.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-40",
    rating: 5,
    body: "Booked online in two minutes, got a text when the fitter was on the way. Way easier than driving to a shop and waiting around.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-40",
    published_at: "2026-09-10T14:30:00+10:00",
  },
  {
    id: 39,
    source: "google",
    author_name: "Dave H.",
    author_photo_url: null,
    rating: 4,
    body: "Good price and the fitter was friendly. Took a bit longer than the quoted window but kept me posted the whole time.",
    reply_body: "Appreciate the feedback, Dave — we're always working on tightening up our time estimates.",
    review_url: "https://g.page/r/fixture-review-39",
    published_at: "2026-09-05T09:15:00+10:00",
  },
  {
    id: 38,
    source: "google",
    author_name: "Michelle T.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-38",
    rating: 5,
    body: "Fantastic! Didn't have to take time off work, they came to my office car park at lunch. Highly recommend.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-38",
    published_at: "2026-08-29T12:00:00+10:00",
  },
  {
    id: 37,
    source: "google",
    author_name: "Callum B.",
    author_photo_url: null,
    rating: 5,
    body: "Price matched a quote I had from another place and still beat their turnaround time. Easy.",
    reply_body: null,
    review_url: null,
    published_at: "2026-08-24T16:45:00+10:00",
  },
  {
    id: 36,
    source: "google",
    author_name: "Amanda K.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-36",
    rating: 3,
    body: "Tyres are fine but had to reschedule once because the fitter's van broke down. Understandable, just a bit inconvenient.",
    reply_body: "Sorry about that, Amanda — we've since added a backup van for exactly this situation. Thanks for your patience.",
    review_url: "https://g.page/r/fixture-review-36",
    published_at: "2026-08-18T11:20:00+10:00",
  },
  {
    id: 35,
    source: "google",
    author_name: "Rohan M.",
    author_photo_url: null,
    rating: 5,
    body: "Booked a set of 4 for my SUV, the whole thing including balancing took about an hour in my own garage. Brilliant.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-35",
    published_at: "2026-08-12T08:00:00+10:00",
  },
  {
    id: 34,
    source: "google",
    author_name: "Sarah L.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-34",
    rating: 4,
    body: "Solid experience overall, would use again. Only reason it's not 5 stars is booking a specific time slot felt a bit limited.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-34",
    published_at: "2026-08-06T13:10:00+10:00",
  },
  {
    id: 33,
    source: "google",
    author_name: "Tom W.",
    author_photo_url: null,
    rating: 5,
    body: "Came home from work to find brand new tyres on the car, no fuss at all. This is how tyre shopping should work.",
    reply_body: "Love hearing this, Tom — thanks for trusting us with it!",
    review_url: "https://g.page/r/fixture-review-33",
    published_at: "2026-07-30T17:40:00+10:00",
  },
  {
    id: 32,
    source: "google",
    author_name: "Grace N.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-32",
    rating: 2,
    body: "Fitter was polite but one of the new tyres had a slow leak within a week and it took a few calls to get it sorted.",
    reply_body: "We're sorry to hear this, Grace — please reach out directly so we can make it right straight away.",
    review_url: "https://g.page/r/fixture-review-32",
    published_at: "2026-07-22T10:05:00+10:00",
  },
  {
    id: 31,
    source: "google",
    author_name: "Liam P.",
    author_photo_url: null,
    rating: 5,
    body: "Cheaper than I expected and no hidden fees at the end. Exactly what was quoted.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-31",
    published_at: "2026-07-15T15:25:00+10:00",
  },
  {
    id: 30,
    source: "google",
    author_name: "Nadia F.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-30",
    rating: 5,
    body: "First time using a mobile tyre service and I'm converted. So much easier than the old way.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-30",
    published_at: "2026-07-09T09:50:00+10:00",
  },
  {
    id: 29,
    source: "google",
    author_name: "Ben C.",
    author_photo_url: null,
    rating: 4,
    body: "Good communication throughout, fitter double-checked torque settings before leaving which I appreciated.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-29",
    published_at: "2026-07-02T14:00:00+10:00",
  },
  {
    id: 28,
    source: "google",
    author_name: "Olivia S.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-28",
    rating: 5,
    body: "Used them for our whole small business fleet, made scheduling around drivers so much simpler.",
    reply_body: "Thanks for trusting us with the fleet, Olivia — always happy to work around your drivers' schedules.",
    review_url: "https://g.page/r/fixture-review-28",
    published_at: "2026-06-25T11:30:00+10:00",
  },
  {
    id: 27,
    source: "google",
    author_name: "Marcus D.",
    author_photo_url: null,
    rating: 5,
    body: "Booked same-day for a puncture emergency and they still made it out within a couple of hours.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-27",
    published_at: "2026-06-18T16:15:00+10:00",
  },
  {
    id: 26,
    source: "google",
    author_name: "Chloe V.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-26",
    rating: 4,
    body: "Really convenient, just wish there were more appointment slots on weekends.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-26",
    published_at: "2026-06-10T08:45:00+10:00",
  },
  {
    id: 25,
    source: "google",
    author_name: "Ethan G.",
    author_photo_url: null,
    rating: 5,
    body: "Price guarantee actually worked — found the same tyre cheaper elsewhere and they matched it without any hassle.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-25",
    published_at: "2026-06-02T13:55:00+10:00",
  },
  {
    id: 24,
    source: "google",
    author_name: "Isabelle M.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-24",
    rating: 5,
    body: "Everything from booking to fitting was seamless. Great communication via text updates too.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-24",
    published_at: "2026-05-27T10:20:00+10:00",
  },
  {
    id: 23,
    source: "google",
    author_name: "Ryan O.",
    author_photo_url: null,
    rating: 3,
    body: "Fitting itself was fine, but had to wait a while on the phone to reschedule when my plans changed.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-23",
    published_at: "2026-05-20T15:35:00+10:00",
  },
  {
    id: 22,
    source: "google",
    author_name: "Zoe A.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-22",
    rating: 5,
    body: "Fitter was super knowledgeable, answered all my questions about tyre types for my car without being pushy.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-22",
    published_at: "2026-05-13T09:00:00+10:00",
  },
  {
    id: 21,
    source: "google",
    author_name: "Harrison K.",
    author_photo_url: null,
    rating: 5,
    body: "Two flats in one week (bad luck!) and they sorted both with mobile appointments within a day each time.",
    reply_body: "Sorry about the run of bad luck, Harrison — glad we could get you sorted quickly both times.",
    review_url: "https://g.page/r/fixture-review-21",
    published_at: "2026-05-05T12:40:00+10:00",
  },
  {
    id: 20,
    source: "google",
    author_name: "Freya J.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-20",
    rating: 4,
    body: null,
    reply_body: null,
    review_url: null,
    published_at: "2026-04-28T17:10:00+10:00",
  },
  {
    id: 19,
    source: "google",
    author_name: "Connor E.",
    author_photo_url: null,
    rating: 5,
    body: "Been using them for two years across three cars now, never had a bad experience.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-19",
    published_at: "2026-04-20T11:00:00+10:00",
  },
  {
    id: 18,
    source: "google",
    author_name: "Ava R.",
    author_photo_url: "https://lh3.googleusercontent.com/a/fixture-18",
    rating: 5,
    body: "Loved not having to sit in a waiting room. Worked from home while they did the tyres outside.",
    reply_body: null,
    review_url: "https://g.page/r/fixture-review-18",
    published_at: "2026-04-14T14:25:00+10:00",
  },
];
